version: '0.4.{build}'

environment:
  QTDIR: C:\Qt\5.8\mingw53_32

install:
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - cd ./StreamControl

build_script:
  - qmake -r -spec win32-g++
  - mingw32-make

after_build:
  - windeployqt release/StreamControl.exe
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: StreamControl\release
    name: StreamControl
